# -*- coding: utf-8 -*-
"""Modelo de Relatório para o Trabalho – Coffee Shops Tia Rosa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pxBBKiO64wuqId7Re8Z6bf-aphvxcx30
"""

# ================================
# Coffee Shops Tia Rosa - Sistema de Gestão
# Versão Google Colab
# ================================

# Estruturas principais
produtos = []        # Lista de dicionários: {"nome": str, "preco": float, "estoque": int}
clientes = []        # Lista de dicionários: {"nome": str, "telefone": str, "email": str}
vendas = []          # Lista de dicionários: {"cliente": str, "itens": list, "total": float}

# ================================
# Funções do Sistema
# ================================

def cadastrar_produto():
    print("\n--- Cadastro de Produto ---")
    nome = input("Nome do produto: ")
    preco = float(input("Preço do produto (R$): "))
    estoque = int(input("Quantidade em estoque: "))
    produtos.append({"nome": nome, "preco": preco, "estoque": estoque})
    print(f"✅ Produto '{nome}' cadastrado com sucesso!\n")

def visualizar_cardapio():
    print("\n--- Cardápio / Produtos ---")
    if not produtos:
        print("❌ Nenhum produto cadastrado.")
    else:
        for i, p in enumerate(produtos, start=1):
            print(f"{i}. {p['nome']} - R${p['preco']:.2f} | Estoque: {p['estoque']}")
    print()

def cadastrar_cliente():
    print("\n--- Cadastro de Cliente ---")
    nome = input("Nome do cliente: ")
    telefone = input("Telefone: ")
    email = input("E-mail: ")
    clientes.append({"nome": nome, "telefone": telefone, "email": email})
    print(f"✅ Cliente '{nome}' cadastrado com sucesso!\n")

def registrar_pedido():
    if not produtos:
        print("\n❌ Não há produtos para vender. Cadastre primeiro.\n")
        return
    if not clientes:
        print("\n❌ Não há clientes cadastrados. Cadastre primeiro.\n")
        return

    print("\n--- Registro de Pedido ---")
    nome_cliente = input("Digite o nome do cliente: ")

    # Verificar se cliente existe
    cliente_encontrado = next((c for c in clientes if c["nome"].lower() == nome_cliente.lower()), None)
    if not cliente_encontrado:
        print("❌ Cliente não encontrado. Cadastre primeiro!\n")
        return

    pedido_itens = []
    total = 0.0

    while True:
        visualizar_cardapio()
        escolha = input("Digite o número do produto para adicionar ao pedido (ou 0 para finalizar): ")
        if escolha == "0":
            break
        if not escolha.isdigit() or int(escolha) < 1 or int(escolha) > len(produtos):
            print("❌ Escolha inválida.")
            continue

        produto = produtos[int(escolha) - 1]
        if produto["estoque"] <= 0:
            print("❌ Produto sem estoque!")
            continue

        quantidade = int(input(f"Quantas unidades de '{produto['nome']}' deseja?: "))
        if quantidade > produto["estoque"]:
            print("❌ Estoque insuficiente!")
            continue

        # Atualiza estoque e pedido
        produto["estoque"] -= quantidade
        subtotal = quantidade * produto["preco"]
        total += subtotal
        pedido_itens.append({"produto": produto["nome"], "quantidade": quantidade, "subtotal": subtotal})
        print(f"✅ {quantidade}x {produto['nome']} adicionados ao pedido. Subtotal: R${subtotal:.2f}")

    if pedido_itens:
        vendas.append({"cliente": nome_cliente, "itens": pedido_itens, "total": total})
        print(f"\n💰 Pedido finalizado para {nome_cliente} | Total: R${total:.2f}\n")
    else:
        print("❌ Nenhum item foi adicionado ao pedido.\n")

def visualizar_vendas():
    print("\n--- Vendas do Dia ---")
    if not vendas:
        print("❌ Nenhuma venda registrada hoje.")
    else:
        total_vendas = 0
        for i, v in enumerate(vendas, start=1):
            print(f"\nVenda {i} - Cliente: {v['cliente']} | Total: R${v['total']:.2f}")
            for item in v["itens"]:
                print(f"  - {item['quantidade']}x {item['produto']} (R${item['subtotal']:.2f})")
            total_vendas += v["total"]
        print(f"\n💵 Total de vendas do dia: R${total_vendas:.2f}\n")

# ================================
# Menu Principal
# ================================
def menu():
    while True:
        print("""
========= Coffee Shops Tia Rosa =========
1. Cadastrar Produto
2. Visualizar Cardápio
3. Cadastrar Cliente
4. Registrar Pedido
5. Visualizar Vendas
0. Sair
""")
        opcao = input("Escolha uma opção: ")

        if opcao == "1":
            cadastrar_produto()
        elif opcao == "2":
            visualizar_cardapio()
        elif opcao == "3":
            cadastrar_cliente()
        elif opcao == "4":
            registrar_pedido()
        elif opcao == "5":
            visualizar_vendas()
        elif opcao == "0":
            print("👋 Obrigado por usar o sistema da Coffee Shops Tia Rosa!")
            break
        else:
            print("❌ Opção inválida. Tente novamente.\n")

# Executa o sistema
menu()

